### PR TITLE
Add point_jacobian and point_jacobian!

### PR DESCRIPTION
**Pull request by rdeits**
(builds on top of #435 )

Still to do: 
- [x] Docstrings
- [x] `@inbounds`
- [x] more careful frame checks

### CODE REVIEW

**Comment by rdeits** [comment]
Rebased onto the amended commit from #435

**Comment by rdeits** [comment]
Ok, all TODOs are TODOne. Should be good once CI passes

**Comment by rdeits** [comment]
I've also pushed the Jacobian IK and basic control demo notebook

**Comment by tkoolen** [comment]
Thanks! Notebook looks great too.

**Pull request merged**
