### PR TITLE
Added Floating SPQuat Joint Type

### PR DESCRIPTION
**Pull request by ryanelandt**
I am working to implement a package in Julia that does soft contact with arbitrary triangular meshes. I need to work with implicit numerical integrators (e.g. Radau5) as the equations are stiff. Solving the implicit system is expensive when orientation is represented as a quaternion for two reasons: 1.) there is an extra state variable requiring an extra autodiff partial and 2.) the magnitude of the quaternion needs to be enforced as a constraint which turns an implicit ODE into a DAE. I added a floating `SPQuat` joint type to lower the cost of implicitly integrating dynamics equations. 

**Two things on note:** 
1. I added a function called `reproject!` which moves the SPQuat away from the singularity if possible. This function should be called at the end of a time step.
2. I added a function called `safe_convert_to_quaternion` which converts rotations to `Quat` without ensuring that the real part of the quaternion is non-negative. This is necessary to circumvent the `copysign` in the `Quat` constructor.

### CODE REVIEW

**Comment by tkoolen** [comment]
Thank you! This looks very good at first glance. Your new package also sounds very interesting.

Do you have a good reference for stereographically projected quaternions? I haven't worked with them before and Rotations.jl was the first place I've ever encountered them. I guess they reference https://pdfs.semanticscholar.org/04c4/0a9ecd9034ddc5b01adc190284a8e5e04f30.pdf, is that what you'd recommend as well?

Re: `copysign` in `Quat`; let's just finally get rid of that in Rotations.

**Comment by ryanelandt** [comment]
You're very welcome. RigidBodyDynamics is a pleasure to use; it feels good to contribute.

I learned of stereographically project quaternions from Rotations.jl as well. That is the reference I would use if I had to point to one.

Getting rid of `copysign` in `Quat` would make a lot of people very happy. (I always manually remove it from the Rotations.jl source code, but I cannot rely on everyone else doing this.)

As currently written, the `reproject!` function will become inactive if `copysign` is removed. Should I:
1. Do nothing and fix this after `copysign` is removed,
2. Add a commit so that `reproject!` works either way or
3. Wait and add additional commits after `copysign` is removed from Rotations.jl?

**Comment by ryanelandt** [comment]
The Rotations PRs are done; thanks for taking the lead on that! I modified this PR to reflect these changes.

Note: I marked the local to global spatial test as broken because the test was comparing random `Quats` to their `principal_values` (I think from a `RotMatrix`). I think that the local to global functions are there for your Munthe-Kaas integrator. I don't understand how these integrators work and don't want to mask issues by naively fixing the test.

**Comment by ryanelandt** [comment]
> Great, just tagged a new version of Rotations: [JuliaLang/METADATA.jl#18010](https://github.com/JuliaLang/METADATA.jl/pull/18010).

Excellent. 

> Shouldn't `principal_value!` also apply to `QuaternionFloating`?

I thought about this, but decided against it as it takes clock cycles and doesn't provide any benefits (numerical and imo otherwise). `principal_value!` can apply to rotational joints as well. This would make a lot of sense in many cases. But I didn't implement it because there are situations where absolute rotations matters find including those that involve winding around rods. (e.g. torque from kite string, things without slip-rings)

> Could you add a test for `principal_value!`? I'm surprised Codecov thinks it's covered, because it clearly isn't.

I'll make that happen tomorrow.

**Comment by tkoolen** [comment]
Alright, thanks very much. I'll merge this now. I'm not sure yet about having `principal_value!` be a no-op for quaternion-parameterized joint types, so I reserve the right to change that later :slightly_smiling_face:.

**Pull request merged**
